version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:30"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:30"
      timezone: Asia/Tokyo
