name: Changelog
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yykamei/actions-update-changelog@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yykamei/actions-git-push@main
        with:
          commit-message: Update CHANGELOG.md
          branch: update-changelog
          force: 'true'
